<Project>
    <PropertyGroup>
        <!--
        Общие свойства сборки для всех проектов лаунчера.
        При изменении TargetFramework убедитесь в актуальности:
        1. Скриптов публикации (publish.py, download_net_runtime.py)
        2. Рабочих процессов CI/CD GitHub Actions (.github/workflows/)
        -->
        <TargetFramework>net10.0</TargetFramework>
        <Version>1.2.2</Version>

        <!--
        CET breaks for people on older, but still supported Windows versions:
        https://github.com/space-wizards/SS14.Launcher/issues/198
        -->
        <AnalysisLevel>latest-recommended</AnalysisLevel>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <NoWarn>$(NoWarn);NU1903;NU1902;NETSDK1206;IL2104;CA1416;CA1707;CA1051;CA1305;CA1310;CA1309;CA1822;CA1861;CA1805;CA1001;CA2201;CA2215;CA1513;CA1866;CA1870;CA2101;CA1711;CA1716;CA1725;CA1860;CA1846;CA1859;CA1872;CA2016;CA2208;CA2211;CA1068;CA1806</NoWarn>
    </PropertyGroup>
</Project>
